site_name: AcronisFSS
site_description: Documentation for AcronisFSS
site_author: Strasser, Joel;
site_url: https://projects.joestr.at/acronisfss/

repo_name: AcronisFSS
repo_url: https://github.com/joestrhq/AcronisFSS
edit_uri: http://github.com/joestrhq/AcronisFSS/edit/website/src/doc/docs

copyright: Copyright &copy; <a href="https://www.joestr.at">joestr.at</a> and all contributors

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - About: about.md
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'blue'

plugins:
  - markdownextradata
  - search:
      lang: en
      prebuild_index: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joestrhq
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joestrhq
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/joestrhq
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/team/joestrhq
